'use strict';

var WK = {"1":{"l":"FOUNDATION","c":"#60a5fa","n":"2-3 RIR. Establish patterns. Full ROM."},"2":{"l":"VOLUME","c":"#34d399","n":"+1 set on compounds. +2.5-5kg where form is solid."},"3":{"l":"INTENSITY","c":"#f59e0b","n":"+5% load. 3-second eccentric every rep."},"4":{"l":"OVERLOAD","c":"#f87171","n":"Drop set last isolation. 0-1 RIR. Deload next week."}};
var CURRENCIES = ["GBP","USD","EUR","AED","SAR","QAR","CHF","CAD","AUD"];
var CURRENCY_SYMBOLS = {GBP:'&#163;',USD:'$',EUR:'&#8364;',AED:'AED',SAR:'SR',QAR:'QR',CHF:'CHF',CAD:'CA$',AUD:'A$'};
function currencySymbol(code){return CURRENCY_SYMBOLS[code]||code;}
var TIPS = [
"Drink water before, during, and after every session. Dehydration cuts performance by 10-20%.",
"Progressive overload is the key. Add 2.5kg when you hit the top of your rep range with clean form.",
"Sleep 7-9 hours. Muscle is built during recovery, not during the workout.",
"Protein target: 1.6-2.2g per kg of bodyweight daily for muscle growth.",
"Warm up with 5-10 minutes of movement before touching weights.",
"The best workout is the one you actually do consistently.",
"Eat a meal with protein and carbs 1-2 hours before training.",
"Track your lifts. What gets measured gets improved.",
"Rest days are not wasted days. Your body gets stronger when it rests.",
"Focus on compound movements first in your session when you have the most energy.",
"A 10% calorie surplus is enough to build muscle without gaining excessive fat.",
"Creatine monohydrate is the most well-researched supplement. 3-5g daily.",
"Mind-muscle connection matters. Slow down and feel the muscle working.",
"Consistency over 12 months beats any perfect program done for 4 weeks.",
"Cold showers after training can reduce soreness and improve recovery.",
"Eat enough carbohydrates. They are your muscles primary fuel source.",
"Do not skip leg day. Your largest muscle groups drive your overall metabolism.",
"A 5-minute stretch after training can significantly reduce next-day soreness.",
"Your first set of the day is a warm-up set. Do not go to failure on it.",
"Foam rolling for 5 minutes before a session improves range of motion.",
"Eat whole foods 80% of the time. The remaining 20% will not derail progress.",
"Breathing technique: exhale on the exertion, inhale on the return.",
"Compound lifts like squat and deadlift release more anabolic hormones.",
"If a muscle is sore, it does not mean it is growing. DOMS is not a requirement.",
"Cardio helps recovery by increasing blood flow to sore muscles.",
"Your grip strength often fails before your back on rows and deadlifts. Use straps.",
"Eat something within 30-60 minutes after training to kick off recovery.",
"Volume drives hypertrophy. More sets per muscle group per week means more growth.",
"Perfect form on 60kg beats sloppy form on 100kg every time.",
"Muscle groups need 48 hours minimum recovery before training them again.",
"Magnesium before bed can improve sleep quality and reduce muscle cramps.",
"A deload week every 4-6 weeks prevents overtraining and keeps progress coming.",
"Stay in a calorie deficit of 300-500 to lose fat while preserving muscle.",
"Caffeine 30-60 minutes before training can improve strength and endurance.",
"Do not compare your beginning to someone else's middle.",
"Free weights recruit more stabiliser muscles than machines.",
"Time under tension matters. A 3-second negative increases muscle damage.",
"Consistency with sleep is more important than any single night of extra rest.",
"Chewing food properly improves digestion and nutrient absorption.",
"The scale lies. Muscle weighs more than fat. Focus on how you look and feel.",
"Lateral raises should be light. Heavy weight leads to traps taking over.",
"Two litres of water per day is a minimum. Add 500ml per hour of exercise.",
"Pre-exhaust a muscle with an isolation exercise to improve mind-muscle connection.",
"Your core is engaged in every major lift. Train it with purpose.",
"Walking 8,000 steps daily burns more total calories than one cardio session.",
"Omega-3 fatty acids reduce inflammation and support joint health.",
"Train the muscles you cannot see in the mirror. Back and hamstrings matter.",
"A longer warm-up set takes you farther in your working sets.",
"Do not train to failure on every set. Leave 1-2 reps in reserve on most sets.",
"The best diet is one you can stick to for years, not weeks."
];
var EX_LIB = [
{n:"Barbell Bench Press",m:"Chest, Front Delts, Triceps",t:"Compound",sets:4,r:"6-10",rest:"3min",note:"Retract scapula, slight arch, bar to lower chest."},
{n:"Incline Dumbbell Press",m:"Upper Chest, Front Delts",t:"Compound",sets:3,r:"8-12",rest:"2min",note:"30-45 degree incline. Control the descent."},
{n:"Incline Barbell Press",m:"Upper Chest, Front Delts",t:"Compound",sets:4,r:"6-10",rest:"3min",note:""},
{n:"Dumbbell Bench Press",m:"Chest, Front Delts, Triceps",t:"Compound",sets:3,r:"8-12",rest:"2min",note:""},
{n:"Cable Fly",m:"Chest",t:"Isolation",sets:3,r:"12-15",rest:"90s",note:"Slight bend in elbows, squeeze at the top."},
{n:"Pec Deck",m:"Chest",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Dips",m:"Lower Chest, Triceps",t:"Compound",sets:3,r:"8-12",rest:"2min",note:"Lean forward for more chest emphasis."},
{n:"Push-Up",m:"Chest, Triceps, Front Delts",t:"Compound",sets:3,r:"15-20",rest:"60s",note:""},
{n:"Barbell Deadlift",m:"Back, Glutes, Hamstrings",t:"Compound",sets:4,r:"4-6",rest:"4min",note:"Neutral spine, push floor away, bar close to body."},
{n:"Sumo Deadlift",m:"Inner Thighs, Glutes, Hamstrings",t:"Compound",sets:4,r:"6-10",rest:"3min",note:"Wide stance, toes turned out 45 degrees."},
{n:"Trap Bar Deadlift",m:"Back, Glutes, Hamstrings, Quads",t:"Compound",sets:4,r:"5-8",rest:"3min",note:""},
{n:"Pull-Up",m:"Lats, Biceps, Rear Delts",t:"Compound",sets:4,r:"6-10",rest:"2min",note:"Dead hang at bottom, chin over bar at top."},
{n:"Lat Pulldown",m:"Lats, Biceps",t:"Compound",sets:4,r:"8-12",rest:"90s",note:"Lean slightly back, pull to upper chest."},
{n:"Seated Cable Row",m:"Mid Back, Rear Delts, Biceps",t:"Compound",sets:4,r:"8-12",rest:"90s",note:"Sit tall, drive elbows back, squeeze at end."},
{n:"Dumbbell Row",m:"Lats, Rear Delts, Biceps",t:"Compound",sets:3,r:"10-12",rest:"90s",note:"Brace on bench, row to hip."},
{n:"T-Bar Row",m:"Mid Back, Lats",t:"Compound",sets:4,r:"8-10",rest:"2min",note:""},
{n:"Face Pull",m:"Rear Delts, Rotator Cuff",t:"Isolation",sets:3,r:"15-20",rest:"60s",note:"Pull to forehead, external rotation at end."},
{n:"Straight Arm Pulldown",m:"Lats",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Rear Delt Fly",m:"Rear Delts",t:"Isolation",sets:3,r:"12-20",rest:"60s",note:""},
{n:"Barbell Back Squat",m:"Quads, Glutes, Hamstrings",t:"Compound",sets:4,r:"6-10",rest:"3min",note:"Hip crease below parallel, knees track toes."},
{n:"Hack Squat",m:"Quads, Glutes",t:"Compound",sets:3,r:"8-12",rest:"2min",note:""},
{n:"Goblet Squat",m:"Quads, Glutes, Core",t:"Compound",sets:3,r:"12-15",rest:"90s",note:"Dumbbell at chest, deep squat."},
{n:"Leg Press",m:"Quads, Glutes, Hamstrings",t:"Compound",sets:4,r:"10-15",rest:"2min",note:""},
{n:"Romanian Deadlift",m:"Hamstrings, Glutes, Lower Back",t:"Compound",sets:4,r:"8-12",rest:"2min",note:"Hinge at hip, slight knee bend, bar close to legs."},
{n:"Bulgarian Split Squat",m:"Quads, Glutes",t:"Unilateral",sets:3,r:"8-12",rest:"2min",note:"Front foot far enough forward to keep shin vertical."},
{n:"Walking Lunges",m:"Quads, Glutes, Hamstrings",t:"Unilateral",sets:3,r:"10-12 each",rest:"90s",note:""},
{n:"Reverse Lunge",m:"Quads, Glutes",t:"Unilateral",sets:3,r:"10-12 each",rest:"90s",note:""},
{n:"Step Up",m:"Quads, Glutes",t:"Unilateral",sets:3,r:"10-12 each",rest:"90s",note:""},
{n:"Hip Thrust",m:"Glutes",t:"Isolation",sets:4,r:"10-15",rest:"90s",note:"Drive through heels, squeeze glutes at top."},
{n:"Glute Bridge",m:"Glutes, Hamstrings",t:"Isolation",sets:3,r:"15-20",rest:"60s",note:""},
{n:"Glute Kickback",m:"Glutes",t:"Isolation",sets:3,r:"15-20",rest:"60s",note:"Full extension, squeeze at the top."},
{n:"Leg Extension",m:"Quads",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:"Pause at top, control the descent."},
{n:"Leg Curl",m:"Hamstrings",t:"Isolation",sets:3,r:"10-15",rest:"60s",note:""},
{n:"Nordic Curl",m:"Hamstrings",t:"Isolation",sets:3,r:"5-8",rest:"2min",note:"Eccentric only. Very challenging."},
{n:"Calf Raise",m:"Calves",t:"Isolation",sets:4,r:"15-20",rest:"60s",note:"Full range of motion, pause at top and bottom."},
{n:"Seated Calf Raise",m:"Soleus",t:"Isolation",sets:3,r:"15-20",rest:"60s",note:""},
{n:"Overhead Press",m:"Front Delts, Side Delts, Triceps",t:"Compound",sets:4,r:"6-10",rest:"3min",note:"Bar from chin to lockout, core tight."},
{n:"Dumbbell Shoulder Press",m:"Front Delts, Side Delts, Triceps",t:"Compound",sets:3,r:"8-12",rest:"2min",note:""},
{n:"Arnold Press",m:"Front Delts, Side Delts",t:"Compound",sets:3,r:"10-12",rest:"90s",note:""},
{n:"Lateral Raise",m:"Side Delts",t:"Isolation",sets:4,r:"12-20",rest:"60s",note:"Slight forward lean, lead with elbows."},
{n:"Cable Lateral Raise",m:"Side Delts",t:"Isolation",sets:3,r:"15-20",rest:"60s",note:""},
{n:"Upright Row",m:"Side Delts, Traps",t:"Compound",sets:3,r:"10-12",rest:"90s",note:""},
{n:"Barbell Curl",m:"Biceps",t:"Isolation",sets:3,r:"8-12",rest:"90s",note:"No swinging, full extension at bottom."},
{n:"Dumbbell Curl",m:"Biceps",t:"Isolation",sets:3,r:"10-12",rest:"60s",note:""},
{n:"Hammer Curl",m:"Biceps, Brachialis",t:"Isolation",sets:3,r:"10-12",rest:"60s",note:""},
{n:"Incline Dumbbell Curl",m:"Biceps",t:"Isolation",sets:3,r:"10-12",rest:"90s",note:""},
{n:"Cable Curl",m:"Biceps",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Preacher Curl",m:"Biceps",t:"Isolation",sets:3,r:"10-12",rest:"90s",note:""},
{n:"EZ Bar Curl",m:"Biceps",t:"Isolation",sets:3,r:"8-12",rest:"90s",note:""},
{n:"Tricep Pushdown",m:"Triceps",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:"Elbows pinned at sides."},
{n:"Rope Pushdown",m:"Triceps",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Skull Crusher",m:"Triceps",t:"Isolation",sets:3,r:"10-12",rest:"90s",note:"Bar to forehead, elbows stay vertical."},
{n:"Overhead Tricep Extension",m:"Triceps",t:"Isolation",sets:3,r:"10-12",rest:"90s",note:""},
{n:"Close Grip Bench Press",m:"Triceps, Chest",t:"Compound",sets:3,r:"8-12",rest:"2min",note:""},
{n:"Plank",m:"Core",t:"Abs",sets:3,r:"30-60s",rest:"60s",note:"Hips level, core braced."},
{n:"Cable Crunch",m:"Abs",t:"Abs",sets:3,r:"15-20",rest:"60s",note:"Contract the abs, not a pulldown."},
{n:"Hanging Leg Raise",m:"Lower Abs, Hip Flexors",t:"Abs",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Ab Wheel Rollout",m:"Core, Abs",t:"Abs",sets:3,r:"10-12",rest:"90s",note:""},
{n:"Russian Twist",m:"Obliques, Abs",t:"Abs",sets:3,r:"20",rest:"60s",note:""},
{n:"Decline Crunch",m:"Abs",t:"Abs",sets:3,r:"15-20",rest:"60s",note:""},
{n:"Side Plank",m:"Obliques, Core",t:"Abs",sets:3,r:"30-45s each",rest:"60s",note:""},
{n:"Dead Bug",m:"Core",t:"Abs",sets:3,r:"10 each",rest:"60s",note:""},
{n:"Kettlebell Swing",m:"Hamstrings, Glutes, Core",t:"Compound",sets:4,r:"15-20",rest:"60s",note:"Hip hinge, not a squat. Explosive hip drive."},
{n:"Box Jump",m:"Quads, Glutes, Calves",t:"Finisher",sets:3,r:"5-8",rest:"90s",note:""},
{n:"Battle Ropes",m:"Full Body",t:"Finisher",sets:3,r:"30s",rest:"30s",note:""},
{n:"Sled Push",m:"Quads, Glutes, Calves",t:"Finisher",sets:4,r:"20m",rest:"90s",note:""},
{n:"Decline Bench Press",m:"Lower Chest, Triceps",t:"Compound",sets:4,r:"8-12",rest:"2min",note:"15-30 degree decline. Feel the lower chest stretch."},
{n:"Chest Press Machine",m:"Chest, Triceps",t:"Compound",sets:3,r:"10-15",rest:"90s",note:"Control the weight on the way back."},
{n:"Low Cable Fly",m:"Upper Chest",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:"Cables set at low position, arc upward."},
{n:"High Cable Fly",m:"Lower Chest",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:"Cables set high, arc downward across body."},
{n:"Svend Press",m:"Chest",t:"Isolation",sets:3,r:"15-20",rest:"60s",note:"Squeeze two plates together throughout entire movement."},
{n:"Landmine Press",m:"Upper Chest, Front Delts",t:"Compound",sets:3,r:"10-12",rest:"90s",note:"Press at an angle, great for shoulder health."},
{n:"Barbell Row",m:"Mid Back, Lats, Rear Delts",t:"Compound",sets:4,r:"6-10",rest:"2min",note:"Overhand grip, pull to lower abdomen, stay horizontal."},
{n:"Pendlay Row",m:"Mid Back, Lats",t:"Compound",sets:4,r:"5-8",rest:"3min",note:"Dead stop on floor each rep. Explosive pull."},
{n:"Chest Supported Row",m:"Mid Back, Rear Delts",t:"Compound",sets:4,r:"10-12",rest:"90s",note:"Chest on incline bench eliminates lower back fatigue."},
{n:"Dumbbell Pullover",m:"Lats, Serratus, Chest",t:"Isolation",sets:3,r:"12-15",rest:"90s",note:"Slight bend in elbows, stretch at top, squeeze lats."},
{n:"Meadows Row",m:"Lats, Mid Back",t:"Compound",sets:3,r:"10-12",rest:"90s",note:"One arm landmine row. Great lat stretch at bottom."},
{n:"Rack Pull",m:"Lower Back, Traps, Glutes",t:"Compound",sets:4,r:"4-6",rest:"4min",note:"Bar just below knees. Overload the top portion of deadlift."},
{n:"Good Morning",m:"Lower Back, Hamstrings, Glutes",t:"Compound",sets:3,r:"10-12",rest:"2min",note:"Hinge at hips, spine neutral, soft knee bend."},
{n:"Barbell Shrug",m:"Traps, Upper Back",t:"Isolation",sets:4,r:"12-15",rest:"60s",note:"Straight up, don't roll shoulders. Hold at top."},
{n:"Dumbbell Shrug",m:"Traps, Upper Back",t:"Isolation",sets:3,r:"15-20",rest:"60s",note:""},
{n:"Front Squat",m:"Quads, Core, Upper Back",t:"Compound",sets:4,r:"5-8",rest:"3min",note:"Elbows high, clean grip or crossed arms. Very upright torso."},
{n:"Pause Squat",m:"Quads, Glutes",t:"Compound",sets:4,r:"5-6",rest:"3min",note:"2-3 second pause at the bottom. Build strength out of the hole."},
{n:"Sissy Squat",m:"Quads",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:"Lean back, knees travel far forward. Use support if needed."},
{n:"Single Leg RDL",m:"Hamstrings, Glutes",t:"Unilateral",sets:3,r:"10-12 each",rest:"90s",note:"Hip hinge on one leg, keep pelvis level throughout."},
{n:"Lying Leg Curl",m:"Hamstrings",t:"Isolation",sets:3,r:"10-15",rest:"60s",note:"Full extension, curl all the way up. Pause at top."},
{n:"Cable Pull-Through",m:"Glutes, Hamstrings",t:"Compound",sets:3,r:"15-20",rest:"60s",note:"Hip hinge movement. Drive hips forward explosively."},
{n:"Donkey Kick",m:"Glutes",t:"Isolation",sets:3,r:"15-20 each",rest:"60s",note:"Keep hips square. Full extension and squeeze at top."},
{n:"Adductor Machine",m:"Inner Thighs",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Abductor Machine",m:"Outer Glutes, Hips",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Sumo Squat",m:"Inner Thighs, Glutes, Quads",t:"Compound",sets:3,r:"10-15",rest:"90s",note:"Wide stance, toes out 45. Knees track over toes."},
{n:"Cable Front Raise",m:"Front Delts",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Dumbbell Front Raise",m:"Front Delts",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:"Alternate arms or both together. Keep slight bend in elbow."},
{n:"Rear Delt Machine",m:"Rear Delts",t:"Isolation",sets:3,r:"15-20",rest:"60s",note:"Set arms parallel. Lead with elbows."},
{n:"Landmine Lateral Raise",m:"Side Delts",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:"One hand on landmine end. Arc upward to shoulder height."},
{n:"Machine Shoulder Press",m:"Front Delts, Side Delts, Triceps",t:"Compound",sets:3,r:"10-15",rest:"90s",note:""},
{n:"Concentration Curl",m:"Biceps",t:"Isolation",sets:3,r:"10-12",rest:"60s",note:"Elbow braced on inner thigh. Full squeeze at top."},
{n:"Spider Curl",m:"Biceps",t:"Isolation",sets:3,r:"10-12",rest:"60s",note:"Chest on incline bench, arms hang free. Strict form."},
{n:"Reverse Curl",m:"Brachialis, Brachioradialis, Forearms",t:"Isolation",sets:3,r:"10-12",rest:"60s",note:"Overhand grip barbell curl. Builds arm thickness."},
{n:"Zottman Curl",m:"Biceps, Brachialis, Forearms",t:"Isolation",sets:3,r:"10-12",rest:"90s",note:"Supinate up, pronate at top, lower with overhand grip."},
{n:"Cable Overhead Tricep Extension",m:"Triceps, Long Head",t:"Isolation",sets:3,r:"12-15",rest:"60s",note:"Cable behind head. Full stretch at bottom."},
{n:"Tricep Dips (Bench)",m:"Triceps, Chest",t:"Compound",sets:3,r:"12-15",rest:"90s",note:"Feet elevated for more challenge. Keep elbows back."},
{n:"Diamond Push-Up",m:"Triceps, Chest",t:"Compound",sets:3,r:"10-15",rest:"60s",note:"Hands form a diamond shape. Elbows tight to body."},
{n:"Wrist Curl",m:"Forearms",t:"Isolation",sets:3,r:"15-20",rest:"45s",note:"Forearms on bench, full range of motion."},
{n:"Reverse Wrist Curl",m:"Forearms",t:"Isolation",sets:3,r:"15-20",rest:"45s",note:""},
{n:"V-Up",m:"Abs, Hip Flexors",t:"Abs",sets:3,r:"15-20",rest:"60s",note:"Meet hands and feet at the top. Keep legs straight."},
{n:"Bicycle Crunch",m:"Abs, Obliques",t:"Abs",sets:3,r:"20 each",rest:"60s",note:"Slow and controlled. Don't pull neck."},
{n:"Hollow Body Hold",m:"Core, Abs",t:"Abs",sets:3,r:"20-40s",rest:"60s",note:"Lower back pressed to floor. Arms and legs off ground."},
{n:"Pallof Press",m:"Core, Obliques",t:"Abs",sets:3,r:"10-12 each",rest:"60s",note:"Press out and hold. Resist rotation. Stand perpendicular to cable."},
{n:"Cable Woodchop",m:"Obliques, Core",t:"Abs",sets:3,r:"12-15 each",rest:"60s",note:"Rotate from high to low. Keep arms straight."},
{n:"Back Extension",m:"Lower Back, Glutes",t:"Abs",sets:3,r:"12-15",rest:"60s",note:"Hinge at hips. Add weight on chest for progression."},
{n:"Hyperextension",m:"Lower Back, Glutes, Hamstrings",t:"Abs",sets:3,r:"12-15",rest:"60s",note:""},
{n:"Dragon Flag",m:"Core, Abs",t:"Abs",sets:3,r:"5-8",rest:"90s",note:"Advanced. Full body lever off bench. Control the descent."},
{n:"Farmer's Carry",m:"Forearms, Traps, Core",t:"Compound",sets:4,r:"30-40m",rest:"90s",note:"Tall posture, heavy dumbbells/kettlebells. Walk with purpose."},
{n:"Turkish Get-Up",m:"Core, Shoulders, Glutes",t:"Compound",sets:3,r:"3-5 each",rest:"2min",note:"Slow and controlled. Keep eye on the weight overhead."},
{n:"Clean and Press",m:"Full Body, Shoulders",t:"Compound",sets:4,r:"5-6",rest:"3min",note:"Explosive pull, catch in front rack, press overhead."},
{n:"Burpee",m:"Full Body",t:"Finisher",sets:4,r:"10-15",rest:"30s",note:""},
{n:"Jump Squat",m:"Quads, Glutes, Calves",t:"Finisher",sets:4,r:"10-12",rest:"60s",note:"Land softly. Immediately descend into next squat."},
{n:"Medicine Ball Slam",m:"Core, Shoulders, Lats",t:"Finisher",sets:4,r:"10-15",rest:"45s",note:"Full extension overhead, slam with maximum force."},
{n:"Sprint (Treadmill)",m:"Quads, Hamstrings, Calves",t:"Finisher",sets:6,r:"20s",rest:"40s",note:""},
{n:"Jump Rope",m:"Calves, Coordination, Cardio",t:"Finisher",sets:5,r:"60s",rest:"30s",note:""},
{n:"Dumbbell Thruster",m:"Quads, Glutes, Shoulders",t:"Finisher",sets:4,r:"10-12",rest:"60s",note:"Squat to press. Keep core braced throughout."}
];

var PLANS = {
free:{name:'Starter',price:0,clientLimit:3,features:{programBuilder:false,paymentTracking:false,messaging:true,analytics:false,scheduling:true,export:false,templates:false}},
pro:{name:'Pro',price:29,currency:'GBP',clientLimit:999,features:{programBuilder:true,paymentTracking:true,messaging:true,analytics:true,scheduling:true,export:true,templates:true}},
business:{name:'Business',price:79,currency:'GBP',clientLimit:999,features:{programBuilder:true,paymentTracking:true,messaging:true,analytics:true,scheduling:true,export:true,templates:true,whiteLabel:true,multiTrainer:true}}
};
var CLIENT_PREMIUM = {price:4.99,currency:'GBP',features:{badges:true,detailedAnalytics:true,bodyComposition:true,dailyTips:true,progressExport:true,extendedHistory:true}};
var CHECKOUT_URLS = {
pro_monthly:'https://buy.stripe.com/YOUR_PRO_MONTHLY_LINK',
pro_annual:'https://buy.stripe.com/YOUR_PRO_ANNUAL_LINK',
business_monthly:'https://buy.stripe.com/YOUR_BUSINESS_LINK',
client_premium:'https://buy.stripe.com/YOUR_CLIENT_PREMIUM_LINK'
};
